import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Hero from "@/components/home/sections/hero/hero";
import News from "@/components/home/sections/news/news";
import Menu from "@/components/home/sections/menu/menu";
import Access from "@/components/home/sections/access/access";
import { getArticles } from "@/libs/newt";
import type { Article } from "@/types/article";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ articles }: { articles: Article[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <News articles={articles} />
        <Menu />
        <Access />
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const articles = await getArticles();

  return {
    props: {
      articles,
    },
  };
};
