import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Hero from "@/components/home/hero";
import News from "@/components/home/news";
import { getArticles } from "@/libs/newt";
import type { Article } from "@/types/article";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ articles }: { articles: Article[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />

        <ul>
          {articles.map((article) => {
            return (
              <li key={article._id}>
                <Link href={`news/${article.slug}`}>{article.title}</Link>
              </li>
            );
          })}
        </ul>
        <News />
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const articles = await getArticles();

  return {
    props: {
      articles,
    },
  };
};
